[package]
name = "sample-19-02"
version = "0.1.0"
authors = ["Tomoaki Masuda <masuda@moonmile.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
