[package]
name = "sample-15-03"
version = "0.1.0"
authors = ["masuda"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
