[package]
name = "sample-14-01"
version = "0.1.0"
authors = ["moonmile <masuda@moonmile.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.22"
serde_json = "1.0.44"
