[package]
name = "sample-18-03"
version = "0.1.0"
authors = ["Tomoaki Masuda <masuda@moonmile.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.1", features = ["thread-pool"] }

